name: Production Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install

      - name: Create React Build
        run: npm run-script build

      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Invalidate CloudFront Cache
        uses: badsyntax/github-action-aws-cloudfront@master
        id: invalidate-cloudfront-cache
        with:
          distribution-id: ${{ secrets.AWS_DISTRIBUTION }}
          aws-region: "us-east-1"
          origin-prefix: "root"
          include-origin-prefix: true
          invalidate-paths: "/index.html,/"
          default-root-object: "index.html"
