name: Production Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: React Build
        run: npm run build
